### ISSUE TITLE
suggestion for improvement of generated method template

### ISSUE THREAD

**Issue by emicklei** [sasha-s/goimpl#1]
currently the generated source looks like this example.
```
func (f formatter) VisitEnum(e *proto3.Enum) {
	panic(errors.New("Not implemented"))
}
```
i like it to become
```
// VisitEnum is part of the proto3.Visitor interface
func (f formatter) VisitEnum(e *proto3.Enum) {
	panic(errors.New("formatter.VisitEnum not implemented"))
}
```
this way it is clear in the comment why this method is defined.

and I changed the panic message to include the package and method name ; they are shown in the stack when panic-ing.

**Comment by sasha-s** [comment]
Done in https://github.com/sasha-s/goimpl/commit/273c8706dbd45659c9bfa9abeb0faf6ee50676fa
